title: Jiyang Gao
description: I'm currently a PhD student at University of Southern California, advised by Prof. Ram Nevatia. My research focus on computer vision, especially activity detection and video analysis. I obtained my B.S. degree from Tsinghua University in 2015. I interned at Sensetime in 2015 and at Google Research in 2017.
theme: 
