title: Jiyang Gao
description: I'm currently a PhD student in University of Southern California, advised by [Prof. Ram Nevatia](http://iris.usc.edu/people/nevatia/). My research focus on computer vision, especially action detection and video analysis. I obtained my B.S. degree from Tsinghua University in 2015.
theme: 
