title: Jiyang Gao
description: I'm currently a PhD student in University of Southern California, advised by Prof. Ram Nevatia. My research focus on computer vision, especially action detection and video analysis. I obtained my B.S. degree from Tsinghua University in 2015.
show_downloads: true
theme: 
