title: Jiyang Gao
description: I'm currently a PhD student in University of Southern California, advised by Prof. Ram Nevatia. My research focus on computer vision, especially activity detection and video analysis. I obtained my B.S. degree from Tsinghua University in 2015. During my undergraduate, I did research with Prof. Zhihua Wang, focused on smart surgery navigation system. I interned at Sensetime during 2015 spring and Google Research during 2017 summer.
theme: 
