title: Jiyang Gao
description: "I'm currently a PhD student at University of Southern California, advised by Prof. Ram Nevatia. I obtained my B.S. degree from Tsinghua University in 2015. Email: jiyangga at usc dot edu"
theme: 
